{
  "uid" : "88b943b2617fde12",
  "name" : "test_xfail_unexpected_pass",
  "fullName" : "vkr_project_tests.test_attach#test_xfail_unexpected_pass",
  "historyId" : "4be046757b2c615a5dd5ca3ae671cff3",
  "time" : {
    "start" : 1649448044370,
    "stop" : 1649448044371,
    "duration" : 1
  },
  "description" : "this test is an xfail that will be marked as unexpected success",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as unexpected success</p>\n",
  "status" : "passed",
  "statusMessage" : "XPASS this test is expecting failure",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7f67be3404c0>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az127-553"
  }, {
    "name" : "thread",
    "value" : "2386-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7f67be3404c0>, reason='this test is expecting failure')" ]
  },
  "source" : "88b943b2617fde12.json",
  "parameterValues" : [ ]
}