{
  "uid" : "21376266ecc502c0",
  "name" : "test_xfail_expected_failure",
  "fullName" : "vkr_project_tests.test_attach#test_xfail_expected_failure",
  "historyId" : "a55201de92fab6edbf92cb844607333f",
  "time" : {
    "start" : 1649448589941,
    "stop" : 1649448589942,
    "duration" : 1
  },
  "description" : "this test is an xfail that will be marked as expected failure",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as expected failure</p>\n",
  "status" : "skipped",
  "statusMessage" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
  "statusTrace" : "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\nvkr_project_tests/test_attach.py:7: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7f2c49b7c310>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az127-553"
  }, {
    "name" : "thread",
    "value" : "2421-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 3,
        "passed" : 0,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "d2736173f54b674f",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/83//#testresult/d2736173f54b674f",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
        "time" : {
          "start" : 1649448213040,
          "stop" : 1649448213040,
          "duration" : 0
        }
      }, {
        "uid" : "fbc83f55ff44ffeb",
        "reportUrl" : "https://YaroslavS1.github.io/VKR_project/82//#testresult/fbc83f55ff44ffeb",
        "status" : "skipped",
        "statusDetails" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
        "time" : {
          "start" : 1649448044346,
          "stop" : 1649448044346,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7f2c49b7c310>, reason='this test is expecting failure')" ]
  },
  "source" : "21376266ecc502c0.json",
  "parameterValues" : [ ]
}